# Generated by Django 4.0.2 on 2022-02-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messireview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='reson',
            new_name='reason',
        ),
    ]
